version: '3'
services:
  model1:
    build: model1/.
  model2:
    build: model2/.
  auth:
    build: auth/.
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/index.html:/app/html:ro